name: graal play

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@latest
      - uses: gluonhq/setup-graalvm@master
        # set GITHUB_TOKEN to avoid exceeding GitHub's API rate limit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # GraalVM version. Default: latest
          graalvm: "22.1.0.1-Final"
          # Java version. Since GraalVM 22, either java11, java17 or java23. Before GraalVM 22, empty. Default: java23
          jdk: "java23"
          # Architecture flag. Available options are 'x86_64' (default) and 'aarch64'. The latter is available for M1 runners starting GraalVM 22.1.
          arch: "x86_64"
      - run: java -version
